### ISSUE TITLE
Thank you for your wonderful package!

### ISSUE THREAD

**Issue by JosephKJ** [GMvandeVen/continual-learning#1]
Hi Gido M. van de Ven, 

Thank you for your well written package. This would be of great contribution to the community. Thanks!

Can you kindly confirm whether you were able to match results with the baseline performances reported in the corresponding papers, by the authors?

Thanks,
Joseph

**Comment by GMvandeVen** [comment]
Hi Joseph,
Thanks! I can confirm that I have comprehensively tested the implemented methods in various settings and that their performances are consistent with results reported elsewhere in the literature (unless differences could be explained; e.g. difference in whether task identity is available during testing or not). I have however not attempted to formally reproduce the results reported in the original papers with their exact task protocols and hyperparameter-settings.
Please continue to let me know if you come across any (potential) issues, for which thanks.
Best,
Gido

**Comment by JosephKJ** [comment]
Sure! And thanks again for your contribution!
