### ISSUE TITLE
Lower/Upper Bound Experiments

### ISSUE THREAD

**Issue by kaustubholpadkar** [GMvandeVen/continual-learning#17]
How to run "None – lower bound" and "Offline – upper bound" experiments? I am not able to find any flags for that.

**Comment by GMvandeVen** [comment]
Thanks for your question, I realise this was indeed not clear from the instructions. You can run these baselines using the following:
- None: `./main.py`
- Offline: `./main.py --replay=offline`

Probably it would have been more intuitive to have flags for these baseline approaches. I might change this when I have some time.

**Comment by kaustubholpadkar** [comment]
Thank you for clearing that up.
