### ISSUE TITLE
Link error

### ISSUE THREAD

**Issue by MingkangXiong** [GMvandeVen/continual-learning#20]
The link of "van de Ven et al. (2022, Nature Machine Intelligence" in "NeurIPS_tutorial.md" shows error.

**Comment by GMvandeVen** [comment]
My apologies, that link is not yet available. You can find a presentation of a workshop version of that paper here: https://virtual.lifelong-ml.cc/poster_67.html. I have updated the page to reflect this. Thanks for letting me know!

**Comment by GMvandeVen** [comment]
The article that is referred to in "NeurIPS_tutorial.md" is now available: https://www.nature.com/articles/s42256-022-00568-3. I have updated the links. Sorry for the delay!
