### ISSUE TITLE
How to create Resnet34

### ISSUE THREAD

**Issue by Peeaak** [GMvandeVen/continual-learning#23]
I am trying to create a resnet34 using the code you provided to conduct the continual learning task, but I have not succeeded. Could you tell me how to create resnet34 using the code you provided?

**Comment by Peeaak** [comment]
@GMvandeVen
GMvandeVen

**Comment by GMvandeVen** [comment]
Thanks for your interest in my code. I'm afraid that at the moment I don't have the time to construct and verify a ResNet34 in the repository. However, with the provided building blocks (see https://github.com/GMvandeVen/continual-learning/tree/master/models) I think that in principle it should be possible to do this.
If you run into more specific issues, I'd be happy to try to help.
