### ISSUE TITLE
Joint training results different for different types of incremental learning?

### ISSUE THREAD

**Issue by toshi2k2** [GMvandeVen/continual-learning#25]
Isn't joint training defined as training done on all the data at the same time? In that case, shouldn't it be the same for all three scenarios of CL? However, the results from the code (and in the paper) are not the same. Is joint training defined differently?

**Comment by toshi2k2** [comment]
So, for joint training (task incremental and domain incremental), the output size is equal to 'within-context' label size (for above example, its 2) and for class incremental its the 'global-label' size which is 10 in the above case. Is my understanding correct?

**Comment by GMvandeVen** [comment]
For domain- and class-incremental learning that is correct. For task-incremental learning the output size is typically taken to be equal to the 'global-label' size, with the provided context label being used to set only those output units of classes in the current task to 'active' (i.e., to have a multi-head output layer).
