### ISSUE TITLE
Single head or multihead task incremental

### ISSUE THREAD

**Issue by COD1995** [GMvandeVen/continual-learning#27]
Hi, there

Is this experiment on task incremental single head or multi head? 

Thanks

**Comment by GMvandeVen** [comment]
Hi, in the [accompanying article](https://www.nature.com/articles/s42256-022-00568-3), most experiments in the task-incremental learning scenario use a multi-headed output layer. Exception are experiments in Supplemantary Note 7, in which there are experiments in the task-incremental learning scenario that use a single-headed output layer.
In the code, when you select the task-incremental learning scenario (using `--scenario=task`), by default a multi-headed output layer will be used, but in this scenario you can instead use a single-headed output layer by additionally using the option `--singlehead`.
Note that experiments in the domain- or class-incremental learning scenario always use a single-headed output layer.
Hope this helps!
